version: '3'

services:
  memcached:
    image: memcached
    restart: always
    ports:
      - 11211:11211

  api:
    build: flask_api_app/
    ports:
      - 8080:8080
    command: gunicorn -b 0.0.0.0:8080 main:app
    depends_on:
      - memcached
