version: '3'

services:
  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379
    # to persist data
    volumes:
      - ./data:/data

  api:
    build: flask_api_app/
    ports:
      - 8080:8080
    command: gunicorn -b 0.0.0.0:8080 main:app
    depends_on:
      - redis
