name: Python test

on:
  push:
    branches: [ "memcached" ]
  pull_request:
    branches: [ "memcached" ]

permissions:
  contents: read

jobs:
  runner-job:
    runs-on: ubuntu-latest
    services:
      memcached:
        build: .
        ports:
          - 11211:11211
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./flask_api_app/requirements.txt
    - name: Lint with Ruff
      run: |
        pip install ruff
        ruff --output-format=github .
      continue-on-error: true
    - name: Test with pytest
      env:
        MEMCACHED_HOST: localhost
        MEMCACHED_PORT: 11211
      run: |
        pip install pytest
        pytest ./flask_api_app