name: Python test

on:
  push:
    branches: [ "mongodb" ]
  pull_request:
    branches: [ "mongodb" ]

permissions:
  contents: read

jobs:
  runner-job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./flask_api_app/requirements.txt
    - name: Lint with Ruff
      run: |
        pip install ruff
        ruff --output-format=github .
      continue-on-error: true
    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.10.0
      with:
        mongodb-version: '6.0'
        mongodb-username: root
        mongodb-password: example
        mongodb-db: test_db
    - name: Test with pytest
      env:
        MONGODB_DBNAME: test_db
        MONGODB_URL: mongodb://root:example@$localhost:27017/
      run: |
        pip install pytest
        pytest ./flask_api_app